# fly.toml app configuration file generated for mediedu-pro on 2025-07-05T16:12:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mediedu-pro'
primary_region = 'sjc'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
