app = "mediedu-pro"
primary_region = "nrt"

[build]

[deploy]
  release_command = "bundle exec rails db:prepare"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.checks]
  [http_service.checks.alive]
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/up"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"
  PORT = "3000"