[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['bundle install']

[phases.build]
cmds = [
  'bundle exec rails assets:precompile'
]

[start]
cmd = 'bundle exec puma -C config/puma.rb'