[build]
builder = "nixpacks"

[deploy]
startCommand = "./bin/railway-entrypoint ./bin/rails server"
healthcheckPath = "/up"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3